- name: Config XFCE on Debian11 - does not ask are password when it's booting ore screen off.
  hosts: "{{ variable_host | default('localhost') }}"
  become: yes
  become_method: 'sudo'

  vars:
   
  vars_prompt:
    - name: name_of_user
      prompt: "Please enter the name of user, for which we are making settings \n (default - 'root'):"
      private: no
      default: root     

  tasks:
    - name: "Add setting - no ask the password when use sudo command"
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        insertafter: "^%sudo	ALL=(ALL:ALL) ALL"
        line: "{{ name_of_user }} ALL=(ALL) NOPASSWD: ALL \n"
        backup: true

    - name: "Add setting - turn on autologin {{ name_of_user }} on botting XFCE"
      ansible.builtin.replace:
        path: "/etc/lightdm/lightdm.conf"
        regexp: "^#autologin-user=$"
        replace: "autologin-user = {{ name_of_user }} # config autologin be ansible \n"
        backup: true  
    
    - name: "Turn off Lock screen when display turn off by timer, for XFCE"
      block:
        - name: Creates directory local setting XFCE at user {{ name_of_user }} to 
          file:
            path: /home/{{ name_of_user }}/.config/autostart
            state: directory
        - name: "Copy file from basic setting to setting for user = {{ name_of_user }} "
          ansible.builtin.copy:
            remote_src: yes
            src: "/etc/xdg/autostart/light-locker.desktop"
            dest: "/home/{{ name_of_user }}/.config/autostart/light-locker.desktop"
        - name: "Add setting to file - for no Lock screen"
          ansible.builtin.lineinfile:
            path: "/home/{{ name_of_user }}/.config/autostart/light-locker.desktop"
            insertafter: EOF
            line: "Hidden=true"
               
                
      
