---
- name: Ansible script for Debian 11+, Install and configrure FosWiki (fom git, on separate disk).
  hosts: "{{ variable_host | default('localhost') }}"
  become_user: '{{ name_of_user }}'
  become_method: 'sudo'

  vars:
# Main configure vars
    path_to_foswiki_engine: '/foswiki-engine'
    path_to_foswiki_database: '/foswiki-database'
    disk_for_foswiki: '/dev/sdb'
    type_of_filesystem_foswiki_disk: 'ext4'
    moutpoint_foswiki_disk: '/foswiki-disk'
# tech vars
    list_soft:
      - apache2
      - git-all
      - parted
      - perl
    list_collections_ansible_galaxy:
      - community.general
      - ansible.posix



  vars_prompt:
    - name: name_of_user
      prompt: "Please enter the name of user, for which we are making settings (default root) \n"
      private: no
      default: root

  tasks:
    - name: install Appache and other soft
      apt:
        update_cache: yes
        pkg: '{{ list_soft }}'
        state: present
      become: yes

    - name: Install ansible-galaxy collections, for work with parted
      ansible.builtin.shell:
        cmd: 'ansible-galaxy collection install {{ item }}'
      with_items: '{{ list_collections_ansible_galaxy }}'

    - name: Create new partition on Second drive for FosWiki data
      community.general.parted:
        device: '{{ disk_for_foswiki }}'
        number: 1
        fs_type: '{{type_of_filesystem_foswiki_disk}}'
        state: present
      become: yes

    - name: Format partition Second drive for FosWiki data
      community.general.filesystem:
        fstype: '{{type_of_filesystem_foswiki_disk}}'
        dev: '{{ disk_for_foswiki }}1'
        force: no  # if filesystem always exst on sdb1- do nothing
        state: present
      become: yes

    - name: 'Create directory for FosWiki mount point - {{moutpoint_foswiki_disk}}'
      ansible.builtin.file:
        path: '{{moutpoint_foswiki_disk}}'
        owner: '{{name_of_user}}'
        group: '{{name_of_user}}'
        mode: u+rwx,g+rwx,o+rwx
        state: directory
      become: yes

    - name: 'Mount FosWiki Drive to {{moutpoint_foswiki_disk}}'
      ansible.posix.mount:
        fstype: '{{type_of_filesystem_foswiki_disk}}'
        src: '{{ disk_for_foswiki }}1'
        path: '{{moutpoint_foswiki_disk}}'
        state: mounted

    - name: Prepare folder on Second drive to put FosWiki Engine
      ansible.builtin.file:
        path: '{{moutpoint_foswiki_disk}}{{path_to_foswiki_engine}}'
        owner: '{{name_of_user}}'
        group: '{{name_of_user}}'
        mode: u+rwx,g+rwx,o+rwx
        state: directory
      become: yes

    - name: Prepare folder on Second drive to put FosWiki Database
      ansible.builtin.file:
        path: '{{moutpoint_foswiki_disk}}{{path_to_foswiki_database}}'
        owner: '{{name_of_user}}'
        group: '{{name_of_user}}'
        mode: u+rwx,g+rwx,o+rwx
        state: directory
      become: yes

    - name: Download FosWiki engine from git
      ansible.builtin.git:
        repo: 'https://github.com/foswiki/distro.git'
        dest: '{{moutpoint_foswiki_disk}}{{path_to_foswiki_engine}}'
        single_branch: yes
        version: master

    - name: Config access right on file FosWiki Engine - give acces for apache user
      ansible.builtin.file:
        path: '{{moutpoint_foswiki_disk}}{{path_to_foswiki_engine}}'
        owner: 'apache'
        group: 'apache'
        mode: u+rwx,g+rx,o+rx
        recurse: yes
        state: directory
      become: yes


#    - name: Make config for Apache - to run FosWiki site
#    - name: Make config for Apache - to allow https connection

